### ISSUE TITLE
Export invalid enum type

### ISSUE THREAD

**Issue by dinfer** [fineshopdesign/cf-wasm#28]
Thank you for your awesome works. I'm not good at rust or wasm.

The enum seems to be exported in a strange way.

<img width="398" alt="image" src="https://github.com/fineshopdesign/cf-wasm/assets/11496403/ef8ba579-d69b-44ef-b939-04fdaf9b2920">

<img width="793" alt="image" src="https://github.com/fineshopdesign/cf-wasm/assets/11496403/59d9ff6e-ef70-4d28-9468-f01ba77cd94c">

I think it should be something like this

```
// 1. enum should not be export as const object
export enum SamplingFilter {
    Nearest: 1;
    Triangle: 2;
    CatmullRom: 3;
    Gaussian: 4;
    Lanczos3: 5;
};
// the 3rd parameter should be a reference to that enum
export function resize(photon_img: PhotonImage, width: number, height: number, sampling_filter: SamplingFilter): PhotonImage;
```

**Comment by fineshop** [comment]
Thanks for opening an issue, fixed in #29
